version: "3.9"

services:
  # App
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: always
    tty: true
    ports:
      - "80:3000"
    networks:
      - app-network

  # Database
  db:
    image: postgres:14.9
    container_name: db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "app-db"
      POSTGRES_USER: "alex"
      POSTGRES_PASSWORD: "pass"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local